spring:
  datasource:
    url: jdbc:mysql://112.126.82.110:3306/pi-admin?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: hvfish
    password: Hvfish@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
opisir:
  jwt:
    header: Authorization
    secret: pipipipipi
    prefix: 'Bearer '
    expired: 120 #\u79D2